map_frame: map
base_frame: base_link
odom_frame: odom

use_tf_scan_transformation: true
use_tf_pose_start_estimate: false
pub_map_odom_transform: true
pub_odometry: false

map_resolution: 0.07
map_size: 1024
map_start_x: 0.5
map_start_y: 0.5
map_multi_res_levels: 4

update_factor_free: 0.4
update_factor_occupied: 0.9
map_update_distance_thresh: 1
map_update_angle_thresh: 0.06
laser_z_min_value: -1.0
laser_z_max_value: 1.0
laser_min_dist: 0.2
laser_max_dist: 8.0

advertise_map_service: false
scan_subscriber_queue_size: 5
scan_topic: scan
tf_map_scanmatch_transform_frame_name: scanmatcher_frame
